title: :)
name: :)
url: http://addcp.com
baseurl: /
author: xiao_cang
description: xiao_cang
port: 3003

exclude: [publish, index_bak.html]
rss_name: feed.xml

highlighter: pygments
pyments:  true
markdown: redcarpet
paginate: 10

permalink:  /:year/:month/:title.html

JW:
  pages_list: custom
  tags_list:
  categories_list:
