title: 呵呵
name: 呵呵
url: http://addcp.com
baseurl: /
author: xiao_cang
description: 呵呵
port: 3000

exclude: [publish, index_bak.html]
rss_name: feed.xml

pygments: true
markdown: redcarpet
paginate: 10

permalink:  /:year/:month/:title.html

JW:
  pages_list: custom
  tags_list:
  categories_list:
